In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/uttamkantidutta/main-dataset-amazon/collected_product_review_final_dataset (1).xlsx

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_excel("/kaggle/input/datasets/uttamkantidutta/main-dataset-amazon/collected_product_review_final_dataset (1).xlsx")

In [5]:
df

,Product_ID,Product_Title,Review_Text,Rating,Product_Category,Review_Month,Helpful_Votes,Verified_Purchase,Product_Price_USD,Sentiment
0,B07T6XMZQZ,"Fintie Stand Case for 6"" Kindle Paperwhite (Fi...",This is my 3td kindle and I love being able to...,4,Computers,2021-11,0,True,21.99,Positive
1,B0C7KBYGN4,"Beelink SER6 PRO Mini PC 11 Pro, Mini Computer...",Build quality is fine and the Windows 11 came ...,2,Computers,2023-01,0,True,649.00,Negative
2,B09G9STJF6,ROOFULL External CD DVD Drive USB 3.0 Premium ...,Would not connect to my computer even with tec...,1,Computers,2023-02,0,True,21.99,Negative
3,B01738GIQG,NiSi 150mm Aluminum Square Filter Holder Speci...,"Like most lenses with bulbous front element, u...",5,Camera & Photo,2022-05,0,True,41.01,Positive
4,B000NK5Z8Y,STK NB-5L Battery For Canon Powershot SD790 El...,Work perfectly.,5,Camera & Photo,2016-01,0,True,13.99,Positive
...,...,...,...,...,...,...,...,...,...,...
199995,B00WSM6W8W,"Koss KSC75 Portable Stereophone Headphones, Si...","The sound was good, but I had to return them. ...",2,Home Audio & Theater,2014-07,0,True,25.32,Negative
199996,B09J2BCP87,"ASUS ROG Strix Scar 15 (2021) Gaming Laptop, 1...",The laptop is great. Plays just about everyth...,4,Computers,2022-04,1,True,2499.99,Positive
199997,B07Q41YB14,Pyle PCA1.5 2x15 Watt Stereo Power Amplifier -...,This amplifier is exactly what I was looking f...,5,All Electronics,2021-01,0,True,28.66,Positive
199998,B00FFVYSMK,Dell Venue 8 32 GB Tablet (Android),My high school son is impressed with everythin...,5,Computers,2014-01,1,True,26.99,Positive
199999,B09DBJCJ5Z,3 Pack [ Apple MFi Certified ]iPhone Charger 6...,I like that it seems to work fast and seems du...,5,Cell Phones & Accessories,2022-11,0,True,18.99,Positive

In [6]:
df[["Review_Text","Sentiment"]]

                                              Review_Text Sentiment
0       This is my 3td kindle and I love being able to...  Positive
1       Build quality is fine and the Windows 11 came ...  Negative
2       Would not connect to my computer even with tec...  Negative
3       Like most lenses with bulbous front element, u...  Positive
4                                         Work perfectly.  Positive
...                                                   ...       ...
199995  The sound was good, but I had to return them. ...  Negative
199996  The laptop is great.  Plays just about everyth...  Positive
199997  This amplifier is exactly what I was looking f...  Positive
199998  My high school son is impressed with everythin...  Positive
199999  I like that it seems to work fast and seems du...  Positive

[200000 rows x 2 columns]

In [9]:
df["Sentiment"].value_counts(normalize = True)*100

Sentiment
Positive    76.160
Negative    17.324
Neutral      6.516
Name: proportion, dtype: float64